### ISSUE TITLE
a brief description of the research question, identifying whether it has inferential or predictive objectives

### ISSUE THREAD

**Issue by FeardaMeow** [sarenehan/stat-504-airbnb#1]
Inferential. What are the most useful predictors of Airbnb rental prices?

**Comment by sarenehan** [comment]
What are the strongest indicators of Airbnb rental prices in Amsterdam? This research question is inferential; we would like to learn which attributes of Airbnb rentals are the strongest indicators of price. Though we cannot make causal inferences due to the observational nature of the data, this question interests us as its answer enables an understanding of what visitors of Amsterdam value in accommodation.
